
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: postgres-backup
spec:
 # Backup the database every day at 2AM
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgres-backup
            image: postgres
            command: ["/bin/sh"]
            args: ["-c", 'rm -rf /var/backups/backup* && echo "$PGPASS" > /root/.pgpass && chmod 600 /root/.pgpass && pg_dump -U doccano -h postgres-svc doccano > /var/backups/backup-$(date +"%m-%d-%Y-%H-%M").sql']
            env:
            - name: PGPASS
              valueFrom:
                secretKeyRef:
                  name: pgpass
                  key: pgpass
            volumeMounts:
              - mountPath: /var/backups
                name: postgres-backup-storage
          restartPolicy: OnFailure
          volumes:
          - name: postgres-backup-storage
            persistentVolumeClaim:
              claimName: postgres-backup-pv-claim
            



