
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: argotest
spec:
 # Backup the database every day at 2AM
  schedule: "0/10 8-16 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: argotest
            image: postgres
            command: ["/bin/sh"]
            args: ["-c", 'echo hej hej argo!!']
          restartPolicy: OnFailure
            



