kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: argotest-claim
  labels:
    app: argotest
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100MiB